### ISSUE TITLE
Gui Doest Not Work For Me

### ISSUE THREAD

**Issue by aarkkappler** [cvzi/py_itunesart#1]
Hi CVZI, No idea if I can send you some logs,,

Python version : 3.6.8

Thank you for your assistance

**Comment by cvzi** [comment]
I think you may have to install [Pillow](https://pypi.org/project/Pillow/) like this: `pip install pillow`

Which OS are you using?

You can start the Gui script from the terminal to see if there is an error log:
```bash
python path_to/py_itunesart/gui.py yourfile.mp3
```

**Comment by aarkkappler** [comment]
yes, with Pillow it works, I think this is something to add in requirements, many thanks

**Comment by cvzi** [comment]
Thanks, I added it to the readme
