### ISSUE TITLE
Feature request, Congrats and Product Recommandation

### ISSUE THREAD

**Issue by aarkkappler** [cvzi/py_itunesart#4]
ok after tested the product I can say 👍 

1) The Tagging part is not enough automatized, and not really relevant in terms of results (ok to make a team/zoom, to see that with you)

2) this is the best part of this product, because it only work s with iTunes, best picture quality, it's really good, I just would like to suggest to add previous old cover deleting function, i did not understand if I have to click or not on "go", or just on the picture, or go and pictures ..." 

But this is the first time I can say this is an amazing beginning !! the best MP3 project after MP3tag and Freyr, you could work on Freyr because it have the best approach of "Apple Music Query" 

Many thanks, congrats for your amazing job !

**Comment by cvzi** [comment]
Do your files already have a correct artist name and title/album?
If the already have that info, I can change the script so that it automatically uses a search result if the artist name and title/album are exactly the same as in the file. Would that help you?

(I don't really want to put a lot of time in this project)

**Comment by aarkkappler** [comment]
As I already said

the metadata is first not reliable, better to start on on the country code, it could be good to start from ALBUM, ARTISTAL and PATH, you could fork freyr, it have a very good base to query iTunes, this is the best approach, pity it's only a downloader, but you can rebuild your script regarding this tool

The Artwork is very good, yes it match, and the good idea, is the fact when this s not sure we can choose, keep in mind that the old pic can help so the removing have to maybe occur after validation...

I really appreciate that your script can bring a lot of saving time, I agree with some (zoom, teams, Webex,...) to help you as I can
