### ISSUE TITLE
Features Request : Automatically Set General Album Information

### ISSUE THREAD

**Issue by aarkkappler** [cvzi/py_itunesart#7]
Because You Artwork Album WONDERFUL, you can Automatically Set Album metadata (Year, Publisher, Genre, ArtistAlbum, Totaltracks,ITUNESCATALOGID,...)

**Comment by cvzi** [comment]
Do you mean, when you select album art with the GUI, it could automatically set the album metadata? Yes I can add that. It should be easy to add it.

**Comment by cvzi** [comment]
This should work now. There is a new checkbox at the top of the window

**Comment by aarkkappler** [comment]
Many thanks
